[package]
name = "todo_api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = { version = "1.0.219", features = ["derive", "std"] }
tokio = { version = "1.45.1", features = ["full"] }
thiserror = "2.0.12"
anyhow = "1.0.98"
